Added definitionName in the moduleDefinitions section
DNNCommunity/DNNDocs pull request #725
Opened 2024-08-27 12:37 UTC by MaiklT

The documentation of the manifest is missing the definitionName in the moduleDefinitions section. This can be different from the friendlyName.

Close #724

2024-08-27 12:47 UTC, bdukes approved these changes
Thanks!

2024-09-28 03:02 UTC, david-poindexter commented
@MaiklT thanks for the contribution.  It appears there is more in this PR that the title and description suggest.  Can you remove the unrelated commits so we can merge this?  Thanks!

2024-09-28 03:04 UTC, david-poindexter requested changes

2024-09-28 03:04 UTC, david-poindexter commented on content/tutorials/server/setup/set-up-iis/set-up-iis-https/index.md
This doesn't appear to be related to the manifest.

2024-09-28 03:04 UTC, david-poindexter commented on images/BindWebsiteSSL.png
This doesn't appear to be related to the manifest.

2024-09-28 03:04 UTC, david-poindexter commented on images/ChangeIndexTxtAttr.png
This doesn't appear to be related to the manifest.

2024-09-28 03:04 UTC, david-poindexter commented on images/DownloadOpenSSL.png
This doesn't appear to be related to the manifest.

2024-09-28 03:04 UTC, david-poindexter commented on images/EditSerialFileWithTextEditor.png
This doesn't appear to be related to the manifest.

2024-09-28 03:04 UTC, david-poindexter commented on images/ImportClientCert.png
This doesn't appear to be related to the manifest.

2024-09-28 03:04 UTC, david-poindexter commented on images/ImportRootCA.png
This doesn't appear to be related to the manifest.

2024-09-28 03:04 UTC, david-poindexter commented on images/InstallOpenSSL.png
This doesn't appear to be related to the manifest.

2024-10-02 07:35 UTC, MaiklT commented on images/BindWebsiteSSL.png
You are right. Please delete this file from the pull request, I always get the Message "Unable to render rich display" and the "Delete file" option is grayed out.

2024-10-02 07:35 UTC, MaiklT commented on images/DownloadOpenSSL.png
You are right. Please delete this file from the pull request, I always get the Message "Unable to render rich display" and the "Delete file" option is grayed out.

2024-10-02 07:35 UTC, MaiklT commented on images/EditSerialFileWithTextEditor.png
You are right. Please delete this file from the pull request, I always get the Message "Unable to render rich display" and the "Delete file" option is grayed out.

2024-10-02 07:35 UTC, MaiklT commented on images/ImportClientCert.png
You are right. Please delete this file from the pull request, I always get the Message "Unable to render rich display" and the "Delete file" option is grayed out.

2024-10-02 07:35 UTC, MaiklT commented on images/ImportRootCA.png
You are right. Please delete this file from the pull request, I always get the Message "Unable to render rich display" and the "Delete file" option is grayed out.

2024-10-02 07:35 UTC, MaiklT commented on images/InstallOpenSSL.png
You are right. Please delete this file from the pull request, I always get the Message "Unable to render rich display" and the "Delete file" option is grayed out.

2024-10-02 07:37 UTC, MaiklT commented on content/tutorials/server/setup/set-up-iis/set-up-iis-https/index.md
I could delete this file from the pull request, but have issues with removing the images.

2024-10-02 19:19 UTC, valadas commented on images/BindWebsiteSSL.png
I don't think we can delete those in the browser (no way I can see)...

Ideally it makes it easier to work on dedicated branches to submit PRs than from main/master/develop

2024-10-23 17:52 UTC, david-poindexter commented on images/ChangeIndexTxtAttr.png
@MaiklT I will just respond to this comment, but the same applies to most of the requests for us to delete your files.  We cannot delate files on your branch, as we do not have the necessary permission to do so.  

It would be best for you to do the following:

* Sync your forked repo with this one.
* Create a branch off of your forked `main` branch and name it as something like `definition-name`.
* Implement only the proposed change.
* Submit a new PR from your `definition-name` branch to the upstream `main`.

Let us know if you decide to go this route and we can simply close this PR.  Thanks.

2024-10-30 14:28 UTC, closed without merging