Added instructions to create a RootCA and a client certificate and bind it to IIS web site
DNNCommunity/DNNDocs pull request #726
Opened 2024-08-28 10:06 UTC by MaiklT

Closes #680

2024-09-28 19:46 UTC, david-poindexter requested changes
@MaiklT perhaps this belongs in a blog post instead of documentation?  This is quite opinionated (not that it is wrong) in general and there are many ways to go about doing this based on personal preference.  What do you think?

2024-09-28 19:46 UTC, david-poindexter commented on content/tutorials/extensions/dnn-manifest-schema/index.md
I don't believe this file belongs in this PR.

2024-10-02 07:19 UTC, MaiklT commented on content/tutorials/extensions/dnn-manifest-schema/index.md
You are right - something got mixed up.

2024-10-02 07:32 UTC, MaiklT reviewed
Please delete this pull request, thanks!

2024-10-02 19:15 UTC, closed without merging