DNN 5 SKOs
DNNCommunity/DNNDocs pull request #730
Opened 2024-10-02 11:00 UTC by Timo-Breumelhof

I realize this is again quite a large PR. :-)
I went through https://www.timo-design.nl/Portals/0/downloads/DotNetNuke-Skin-Objects-DNN5.pdf and added all SKOs that are still valid..
When this is integrated I'll redirect that URL to DNNDOCS.

I checked te markdown, but it would be nice if someone could check my work too.
It was quite a bit of work and I'm seeing stars now ;-)

`FYI I prefer change-requests for any issue on one of the individual SKO pages as I generate the MD from an Open Content template.`

2024-10-02 19:42 UTC, valadas requested changes
Awesome work, just noted below something missing for the Logo one...

2024-10-02 19:42 UTC, valadas commented on content/tutorials/themes/theme-objects/logo/index.md
I added some time ago support for directly injecting SVG Images for the logo instead of creating an IMG tag.

https://github.com/dnnsoftware/Dnn.Platform/blob/9f4833f5dcba24e0dbd194338c2a50a03a43da83/DNN%20Platform/Website/admin/Skins/Logo.ascx.cs#L40-L41

And now that I am looking at the code, we also have support for 2 css classes (the image and the link)

2024-10-03 10:51 UTC, Timo-Breumelhof commented on content/tutorials/themes/theme-objects/logo/index.md
Right, fixed with last commit

2024-10-03 12:11 UTC, valadas approved these changes
Looks good to me

2024-10-10 16:34 UTC, merged